# Generated by Django 2.0.6 on 2018-09-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WQMT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.PositiveIntegerField(db_column='Delivery')),
                ('issue_category', models.CharField(db_column='Issue Category', max_length=200)),
                ('issue', models.CharField(db_column='Issue', max_length=200)),
                ('detail', models.TextField(db_column='Detail')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Create Datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Update Datetime')),
            ],
            options={
                'db_table': 'APP_WQMT',
            },
        ),
    ]
